"""concept 领域端口协议（由 infrastructure 层实现）"""
import datetime
from typing import Protocol, runtime_checkable

from .models import ConceptEtfMap, ConceptStock, ConceptSummary


@runtime_checkable
class IConceptRepo(Protocol):
    """概念股池仓储接口"""
    async def load_etf_map(self) -> list[ConceptEtfMap]: ...
    async def upsert_etf_map(self, records: list[ConceptEtfMap]) -> None: ...
    async def get_latest_stocks(self, concept: str) -> list[ConceptStock]: ...
    async def upsert_stocks(self, date: datetime.date, records: list[ConceptStock]) -> None: ...
    async def get_all_summaries(self) -> list[ConceptSummary]: ...


@runtime_checkable
class IConceptCache(Protocol):
    """概念股池缓存接口"""
    async def get_concept(self, name: str) -> list[ConceptStock] | None: ...
    async def set_concept(self, name: str, stocks: list[ConceptStock]) -> None: ...
    async def get_list(self) -> list[ConceptSummary] | None: ...
    async def set_list(self, summaries: list[ConceptSummary]) -> None: ...
